version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/engine"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/client/Orchitect.Client.Web"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"
  
  - package-ecosystem: "cargo"
    directory: "/client/Orchitect.Client.Cli"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"